### ISSUE TITLE
Knjižnica emojifont

### ISSUE THREAD

**Issue by jaanos** [majaabraham/APPR-2020-21#1]
Vidim, da si v `install.R` poskrbela za namestitev knjižnice `emojifont`, s čimer si si zagotovila, da se ti projekt požene v Binderju. Žal je zaradi take namestitve grajenje slike dolgotrajnejše, tako da sem v jaanos/APPR-docker@b2e66c70569b4716acd7655b7afa3776af804a2c poskrbel, da je knjižnica na voljo že v osnovni sliki. Tako lahko nameščanje v `install.R` odstraniš in tako poskrbiš za hitrejše zaganjanje projekta v Binderju po novih commitih.

**Comment by majaabraham** [comment]
Knjižnico sem odstranila. Zahvaljujem se za dodatek v osnovni sliki.
